version: "3.2"
services:
  backend:
    restart: always
    container_name: backend
    command : bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./book_list_backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command : npm start
    container_name: frontend
    build:
      context: ./book-list-frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend